### ISSUE TITLE
plotHeatmap function

### ISSUE THREAD

**Issue by Terskikh** [lmweber/diffcyt#10]
Dear Lukas,

I am using diffcyt packege following option number 1 from your tutorial. In the end of analysis I get output which can be displayed using heatmap and plotHeatmap function.
I was wondering if it is possible to custamize the option to display **p_val** instead of **p_adj** when I plot a hetmap with results. I am sorry if you mentioned it in your tutorial and I missed it. 

Thank you in advance!
Best,
Ekaterina

**Comment by rfbrondum** [comment]
I have a request for the same function, so I'll just put it here:

It would be nice to have an option to annotate samples based on an outcome/group in the right heatmap. As it is now samples may be ordered according to group, but otherwise it seems you have to rely on sample names for e.g. healthy vs sick, so I suggest to highlight this with an annotation on the columns similar to the annotation for significance shown for the rows.

**Comment by lmweber** [comment]
Hi, thanks for the comments, and sorry for the delay.

The plotting functions in the CATALYST package have a number of additional options, and also much improved formatting, so I would suggest trying these instead. There are examples available in the CATALYST vignettes (http://bioconductor.org/packages/CATALYST), and also our associated CyTOF workflow (http://bioconductor.org/packages/cytofWorkflow). Does this help?
