### ISSUE TITLE
CONTRAST DOUBT

### ISSUE THREAD

**Issue by DomenicoSkyWalker89** [lmweber/diffcyt#15]
Hi @lmweber ,
thanks for the pakage and the support.
I have a doubt regarding the contrast. I have two groups (CTRL and TREATED), using contrast (0,1) all p value show no significance  but changing contrast (1,0) five population are different. I also find this last result using the contrast (-1,1). This make me confused.

Thanks,
Domenico

**Comment by markrobinsonuzh** [comment]
@DomenicoSkyWalker89 

You need to give a complete description. I wouldn't expect contrasts (0,1) and (1,0) to give similar results, because they are testing *different parameters* of the model. And, (-1, 1) is again testing something different. I would suggest having a read through perhaps the limma or edgeR user's guide (e.g., the case studies) to get a handle on how to pair design matrices and contrasts. Or, a general resource on linear modeling.

If you ask a question here, please give full details, e.g., what is the design matrix?

**Comment by DomenicoSkyWalker89** [comment]
Sorry for the few information.
I followed the CATALYST workflow using flow cytometry data.

![image](https://user-images.githubusercontent.com/53559811/78787921-5c1d1600-79ab-11ea-9257-09830f1eae03.png)

**Comment by feanaros** [comment]
hi, @DomenicoSkyWalker89 did you solve the issue?

**Comment by DomenicoSkyWalker89** [comment]
Dear @feanaros,

Yes, I did. It was a bit difficult at first, but you can follow the explanation here (https://github.com/lmweber/diffcyt/issues/5) or delve into the EdgeR user guide.

Let me know If you need more (in private).


Best,

D

**Comment by feanaros** [comment]
@DomenicoSkyWalker89 thank you! I would ask you something more of Is It possible, how can i contact you?

**Comment by DomenicoSkyWalker89** [comment]
Sure! https://scholar.google.it/citations?user=sS2lKPwAAAAJ&hl=it
