### ISSUE TITLE
very early error reading .fcs files in 

### ISSUE THREAD

**Issue by jenkinmt** [lmweber/diffcyt#34]
Hey,
I'm using the following code from the workflow vignette to read my .fcs files into diffcyt pipeline. 
files <- list.files(
  path = "path/to/files", pattern = "\\.fcs$", full.names = TRUE
)
d_flowSet <- read.flowSet(
  files, transformation = FALSE, truncate_max_range = FALSE
). 
It is returning the following error message:
Error in frameList[isFrame] : invalid subscript type 'list'

I was wondering what the way around this is?

**Comment by HelenaLC** [comment]
Could you print `files`, please?

**Comment by jenkinmt** [comment]
that returns: character(0)

**Comment by HelenaLC** [comment]
Okay. Well that means no files match your `list.files()` call, i.e., there were no files find in `"path/to/files"` with pattern `\.fcs$`. Two thoughts: i) I believe it should be `\\.fcs$`, but not entirely sure; ii) try adding `ignore.case = TRUE` since your files might end with "FCS" vs. "fcs". 

Definitely, make sure to print `files` prior to attempting to read them in with `read.flowSet`.Of course, it'd be nicer if `read.flowSet` returned a more intuitive message such as "no valid FCS files" or "input files are empty". But if `files` is `characer(0)`, there are no files to read in, and an error is no surprise...

**Comment by jenkinmt** [comment]
thank you! I got my files to read in properly but now am working through an issue with the prepareData function and wrapper diffcyt() functions that are in another thread
