### ISSUE TITLE
createContrast help

### ISSUE THREAD

**Issue by shanh1** [lmweber/diffcyt#47]
Hi there,

I am an R and CyTOF beginner looking at some AML and MDS patient data.

My conditions are 5 different timepoints: T1, T2, T3, T4 and T5

I have 8 patients who have received DLI and 6 patients who have not received DLI, but all are AML/MDS patients. The DLI and non-DLI patients have not been specified, as I thought I could just subset them downstream.

If I want to compare T1 to T2, T2 to T3, T3 to T4 etc. for each patient, how would I set up the contrast to do this? How can I subset the patients, instead of looking at every single patient for every single time point?

I would have just separated on DLI and no DLI instead of timepoint, but the timepoint is important as it specifies pre-transplant and post-transplant samples for the patients. It would have been too simple to just state DLI and no DLI.

Thank you kindly!

Shan

**Comment by markrobinsonuzh** [comment]
Hi Shan,

It may be worth talking to a statistician at your local institution to help you design the model and contrasts that you want, for what you want to answer. This may be hard to do over GitHub issues.

That said, one thing I'm confused about is how you will be able to compare T1-T2, T2-T3, etc. *for each patient*, because there you do not have replicates. Or maybe you can set it up as a straightforward paired design across multiple patients? In that case, you could specify it with the design matrix and you don't need a contrast (or your contrast is simply a parameter in the model).

But I'm not sure that I fully understand your experiment design.

Cheers, Mark
