### ISSUE TITLE
How to use diffcyt to identify differentially-expressed proteins/biomarkers of a cluster in flow cytometry data?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [lmweber/diffcyt#50]
Hi there, 

The tutorial (https://www.bioconductor.org/packages/release/bioc/vignettes/diffcyt/inst/doc/diffcyt_workflow.html) is very useful, but it only shows how to perform the analysis between conditions. 

I had performed clustering using `CATALYST`. 

Would you mind advising me how to adjust the codes, especially `diffcyt::createDesignMatrix` and `contrast` to identify differentially-expressed proteins (biomarkers) of a cluster compared to every other cluster, done for each cluster as in DEGs for scRNAseq analyses? Or is it not possible?

Thank you for your help!

**Comment by markrobinsonuzh** [comment]
hi @denvercal1234GitHub,

Yeah, I mean, `diffcyt` is methodology for performing analysis between conditions, not between clusters .. so, for finding marker genes, I suggest that you use something else. For example, you might be able to use the same `findMarkers` function in `scran` that is used in scRNA-seq marker DE detection, since the data used in `CATALYST` is a `SingleCellExperiment` object. I have actually never done this, because this is not typically the way that people do it for cytometry (generally, people pick markers to use in the first place). But, from a stats perspective, it should still work.

Cheers, Mark

**Comment by purisuto** [comment]
See stat_test_expression() in this package
https://github.com/kordastilab/ImmunoCluster/blob/master/README.md
