### ISSUE TITLE
customized weight in testDS_LMM

### ISSUE THREAD

**Issue by fionarhuang** [lmweber/diffcyt#7]
Hi Lukas,
I made some edits to testDS_LMM & testDS_limma. The change is summarized as below.
1. add droplevels to testDS_LMM & testDS_limma
[here](https://github.com/fionarhuang/diffcyt/blob/fix_weight/R/testDS_LMM.R#L211)
[here](https://github.com/fionarhuang/diffcyt/blob/fix_weight/R/testDS_limma.R#L218)
This is to remove levels that are actually not in `cluster_id`. 

2. allow customized weights:
[here](https://github.com/fionarhuang/diffcyt/blob/fix_weight/R/testDS_LMM.R#L221)
You would see that it allows the version to choose  `TRUE` or `FALSE`.  In this way, it would not affect users who are using `diffcyt`.

3. fix the bug when using `weights = NULL`
[here](https://github.com/fionarhuang/diffcyt/blob/fix_weight/R/testDS_LMM.R#L258)
I add a second `cbind` to fix the error that occurs in  combining a `data.frame` and `NULL`.  

Please let me know whether it works

**Comment by lmweber** [comment]
Hi Fiona, sorry for the delay, and thanks for preparing this so clearly. I have now included the changes from both (2) and (3) in `master` branch, and pushed them to GitHub and Bioconductor `devel`.

For (2), I made a few minor modifications to the code and comments, but I think this all made sense. It now allows users to input a vector of custom weights if they want to, while user behavior for everyone else is unchanged (using either `TRUE` or `FALSE`).

For (3), this was definitely a bug. Thanks for finding it.

However I have not included (1) for now. Dropping the unused levels of `cluster_id` can cause problems later in the function, because I use `nrow = nlevels(cluster_id) ...` when creating the final `SummarizedExperiment`. Let me know what you needed this for, and I will think about how best to address it.

I also used `git cherry-pick` to split it up into separate commits, so it is easier to revert later if there are unexpected problems. Thanks!
